import { NextResponse } from 'next/server';
import { Game } from '@/app/types';
import { sports } from '@/app/lib/sports';
import { supabase } from '@/app/lib/supabase';
// force dynamic
export const dynamic = 'force-dynamic';

export async function GET() {
  console.log('Summoning daily scrolls');
  try {
    // Get today's date in Eastern Time (YYYY-MM-DD format)
    const todayET = new Date(new Date().toLocaleString('en-US', { timeZone: 'America/New_York' }));
    const todayDateString = todayET.toISOString().split('T')[0];
    
    // Get today's schedule from API
    const allSchedules = await Promise.all(
      sports.map(async (sport) => {
        const url = `${process.env.API_BASE_URL}/${sport.key}/events?apiKey=${process.env.ODDS_API_KEY}`;
        const response = await fetch(url);
        if (!response.ok) {
          console.error(`Failed to fetch ${sport.name}:`, response.status);
          return [];
        }
        const data = await response.json();
        
        // Filter and transform games for today
        const todayGames = data
          .filter((game: Game) => {
            if (!game.commence_time) return false;
            const gameTimeET = new Date(new Date(game.commence_time).toLocaleString('en-US', { timeZone: 'America/New_York' }));
            const gameDateString = gameTimeET.toISOString().split('T')[0];
            return gameDateString === todayDateString;
          })
          .map((game: Game) => ({
            // id: auto-generated UUID by database
            game_id: game.id,                    // text
            sport_key: game.sport_key,           // text
            sport_name: sport.name,              // text (NHL, NBA, etc)
            game_date: todayDateString,          // date (YYYY-MM-DD)
            commence_time: game.commence_time,   // timestamp with time zone
            home_team: game.home_team,           // text
            away_team: game.away_team,           // text
            home_score: null,                    // integer (null for upcoming games)
            away_score: null,                    // integer (null for upcoming games)
            completed: false,                    // boolean
            // last_updated: auto-generated by database
          }));
        
        return todayGames;
      })
    );
    
    // Flatten the array
    const allGames = allSchedules.flat();
    
    console.log(`📅 Found ${allGames.length} games for ${todayDateString}`);
    
    if (allGames.length === 0) {
      return NextResponse.json({ message: 'No games scheduled for today' }, { status: 200 });
    }
    
    // Use UPSERT to avoid duplicates if this runs multiple times
    const { data, error } = await supabase
      .from('games')
      .upsert(allGames, { onConflict: 'game_id' })
      .select();
    
    if (error) {
      console.error('Error storing schedule:', error);
      return NextResponse.json({ error: 'Failed to store schedule', details: error }, { status: 500 });
    }
    
    console.log(`✅ Successfully stored ${data?.length || 0} games`);
    
    return NextResponse.json({ 
      success: true,
      message: 'Schedule stored successfully',
      gamesStored: data?.length || 0,
      date: todayDateString
    }, { status: 200 });
  } catch (error) {
    console.error('Error storing schedule:', error);
    return NextResponse.json({ 
      success: false,
      error: 'Failed to store schedule',
      details: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 });
  }
}